"""Strict generated reservation format and reversible service activation."""

import re
from dataclasses import dataclass
from ipaddress import IPv4Address
from pathlib import Path

from vmctl.config import Configuration
from vmctl.errors import VmctlError
from vmctl.models import validate_name
from vmctl.utils.atomic import atomic_remove, atomic_write
from vmctl.utils.subprocess import Runner

WARNING = "# Generated by vmctl. Do not edit manually; IP reservations are managed by vmctl."


@dataclass(frozen=True)
class Reservation:
    mac: str
    ip: IPv4Address
    name: str
    vmid: int | None = None


def parse_reservations(text: str) -> list[Reservation]:
    if text.strip() and text.splitlines()[0] != WARNING:
        raise VmctlError("Reservation file does not have the vmctl generated-file warning")
    result: list[Reservation] = []
    vmid: int | None = None
    for line in text.splitlines():
        if line == WARNING or not line.strip():
            continue
        metadata = re.fullmatch(r"# vmctl-vmid=([1-9][0-9]*)", line)
        if metadata:
            if vmid is not None:
                raise VmctlError("Duplicate reservation VMID comment")
            vmid = int(metadata[1])
            continue
        match = re.fullmatch(
            r"dhcp-host=((?:[0-9a-fA-F]{2}:){5}[0-9a-fA-F]{2}),([^,]+),([^,]+),infinite", line
        )
        if match is None:
            raise VmctlError(f"Unrecognized reservation line: {line!r}")
        try:
            reservation = Reservation(
                match[1].upper(), IPv4Address(match[2]), validate_name(match[3]), vmid
            )
        except ValueError as exc:
            raise VmctlError(f"Invalid reservation IP: {match[2]}") from exc
        result.append(reservation)
        vmid = None
    if vmid is not None:
        raise VmctlError("Reservation VMID comment has no DHCP host")
    for attribute in ("mac", "ip", "name"):
        if len({getattr(entry, attribute) for entry in result}) != len(result):
            raise VmctlError(f"Duplicate reservation {attribute}")
    return result


def render_reservations(reservations: list[Reservation]) -> str:
    lines = [WARNING]
    for entry in sorted(reservations, key=lambda r: int(r.ip)):
        if entry.vmid is not None:
            lines.append(f"# vmctl-vmid={entry.vmid}")
        lines.append(f"dhcp-host={entry.mac.upper()},{entry.ip},{entry.name},infinite")
    text = "\n".join(lines) + "\n"
    parse_reservations(text)
    return text


class DnsmasqReservations:
    def __init__(self, config: Configuration, runner: Runner) -> None:
        self.config, self.runner = config, runner
        self.path = config.path(config.host.network.reservations)

    def _run(self, binary: str, *args: str) -> None:
        self.runner.run(
            [self.config.host.binaries.get(binary, binary), *args],
            timeout=self.config.host.proxmox.command_timeout,
        )

    def read(self) -> list[Reservation]:
        if self.path.is_symlink():
            raise VmctlError(f"Refusing symlink reservation file: {self.path}")
        return parse_reservations(self.path.read_text()) if self.path.exists() else []

    def validate_live(self) -> None:
        self._run(
            "dnsmasq",
            "--test",
            "--conf-file=" + str(self.config.path(self.config.host.network.dnsmasq_config)),
            *("--conf-dir=" + spec for spec in self._conf_dirs()),
        )

    def _conf_dirs(self) -> list[str]:
        result: list[str] = []
        for spec in self.config.host.network.dnsmasq_conf_dirs:
            directory, *suffixes = spec.split(",")
            result.append(",".join((str(self.config.path(directory.strip())), *suffixes)))
        return result

    def preflight(self) -> None:
        self.read()
        self.validate_live()
        self._run("systemctl", "is-active", "--quiet", self.config.host.network.service)
        # Command-line includes are declared explicitly, without parsing service shell scripts.
        self._check_included(self.config.path(self.config.host.network.dnsmasq_config), set())

    def _check_included(self, root: Path, visited: set[Path]) -> None:
        def selected(name: str, suffixes: list[str]) -> bool:
            if (
                name.startswith(".")
                or name.endswith("~")
                or (name.startswith("#") and name.endswith("#"))
            ):
                return False
            return all(
                name.endswith(s[1:]) if s.startswith("*") else not name.endswith(s)
                for s in suffixes
            )

        def includes(path: Path) -> bool:
            path = path.resolve()
            if path in visited:
                return False
            visited.add(path)
            for raw in path.read_text().splitlines():
                line = raw.strip()
                if line.startswith("conf-file="):
                    child = Path(line.removeprefix("conf-file=").strip())
                    if child.resolve() == self.path.resolve() or includes(child):
                        return True
                elif line.startswith("conf-dir=") and includes_directory(
                    line.removeprefix("conf-dir=")
                ):
                    return True
            return False

        def includes_directory(spec: str) -> bool:
            fields = [field.strip() for field in spec.split(",")]
            directory, suffixes = Path(fields[0]), fields[1:]
            if directory.resolve() == self.path.parent.resolve() and selected(
                self.path.name, suffixes
            ):
                return True
            if directory.exists():
                for child in directory.iterdir():
                    if (
                        child.is_file()
                        and child != self.path
                        and selected(child.name, suffixes)
                        and includes(child)
                    ):
                        return True
            return False

        if not includes(root) and not any(includes_directory(spec) for spec in self._conf_dirs()):
            raise VmctlError(
                f"dnsmasq config must include {self.path}. If the service loads its directory "
                "via --conf-dir or -7 (Debian CONFIG_DIR), declare that same directory and "
                "suffix filters in [network].dnsmasq_conf_dirs in the server config.toml. "
                "Otherwise add an include to the service's main configuration. "
                "vmctl does not edit manually managed config"
            )

    def _restart(self) -> None:
        service = self.config.host.network.service
        self._run("systemctl", "restart", service)
        self._run("systemctl", "is-active", "--quiet", service)

    def write(self, entries: list[Reservation]) -> None:
        self.read()
        previous = self.path.read_bytes() if self.path.exists() else None
        data = render_reservations(entries).encode()
        if previous == data:
            return
        candidate_validated = False

        def validate_temp(path: Path) -> None:
            nonlocal candidate_validated
            parse_reservations(path.read_text())
            self._run("dnsmasq", "--test", f"--conf-file={path}")
            candidate_validated = True

        # Even a post-replace fsync failure requires restoring the previous file.
        try:
            atomic_write(self.path, data, mode=0o644, validate=validate_temp)
            self.validate_live()
            self._restart()
        except (VmctlError, OSError, KeyboardInterrupt) as original:
            if not candidate_validated:
                raise VmctlError(
                    f"DHCP candidate rejected; previous configuration retained: {original or 'Interrupted'}"
                ) from original
            try:
                if previous is None:
                    atomic_remove(self.path)
                else:
                    atomic_write(self.path, previous, mode=0o644)
                self.validate_live()
                self._restart()
            except (VmctlError, OSError) as rollback:
                raise VmctlError(
                    f"DHCP update failed: {original}; restoration also failed: {rollback}. Check {self.path} and dnsmasq"
                ) from original
            raise VmctlError(
                f"DHCP update failed; previous configuration restored: {original}"
            ) from original

    def add(self, reservation: Reservation) -> None:
        self.write([*self.read(), reservation])

    def remove_mac(self, mac: str) -> None:
        entries = self.read()
        remaining = [entry for entry in entries if entry.mac != mac.upper()]
        if len(entries) != len(remaining):
            self.write(remaining)
