[presets.small]
cpu = 2
memory_mib = 2048
disk_gib = 20

[presets.normal]
cpu = 4
memory_mib = 8192
disk_gib = 40

[presets.large]
cpu = 8
memory_mib = 16384
disk_gib = 80

[presets.heavy]
cpu = 12
memory_mib = 32768
disk_gib = 120
